# Generated by Django 3.2.25 on 2024-05-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240510_1354'),
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
    ]
