# Generated by Django 3.2.25 on 2024-04-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200211_1303'),
        ('products', '0003_product_has_sizes'),
    ]

    operations = [
    ]
